--------------------------------------------------------
--  File created - Thursday-December-23-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER2
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUSTOMER2" 
   (	"ID" NUMBER(11,0), 
	"USERNAME" VARCHAR2(45 BYTE), 
	"PASSWORD" VARCHAR2(1000 BYTE), 
	"FIRST_NAME" VARCHAR2(45 BYTE), 
	"LAST_NAME" VARCHAR2(45 BYTE), 
	"EMAIL" VARCHAR2(45 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CUSTOMER2
SET DEFINE OFF;
Insert into SYSTEM.CUSTOMER2 (ID,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL) values (90,'pera','$2a$10$Bww36JXJ6IBFJW5tbGQ52u6eHfqdjbl4CkAdVXf.ifEEjuL9A9pny','pera','peric','pera@test.com');
Insert into SYSTEM.CUSTOMER2 (ID,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL) values (101,'admin','$2a$10$h73mhZxHVBIMlxQZe/SmpuVZAWJ9nCfGb7TjwwEghkDcFh22RhSh6','admin','admin','admin@admin.com');
Insert into SYSTEM.CUSTOMER2 (ID,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL) values (102,'manager','$2a$10$emD.F8I.uib7pZKjgfyE5ujVtG5HmydvCzFOCRjTixhVKiWLy8hoG','manager','manager','manager@test.com');
Insert into SYSTEM.CUSTOMER2 (ID,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL) values (121,'mile','$2a$10$ozciSDCaBA9pLIn8bTY0Z.G7iIkFhi0d9jCFFdrpGrtVAGkwCpDXW','Mile','Milic','mile@test.com');
Insert into SYSTEM.CUSTOMER2 (ID,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL) values (145,'zika','$2a$10$/D4p7mOMay9KznTfLnE.z.gJRAn.6VVtJblNuyXs.JbVG25INZr22','Zika','Zikic','zix@tets.com');
Insert into SYSTEM.CUSTOMER2 (ID,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL) values (89,'mix','$2a$10$cNeteU.7gxZVBPNYSAqhoOYGH0G/kZkWPZ2wYm/Jrz7JEYmpk17Ga','milos','radovic','mix@test.com');
--------------------------------------------------------
--  DDL for Index SYS_C008350
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008350" ON "SYSTEM"."CUSTOMER2" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER2
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUSTOMER2" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
